name: Docker test

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build and deploy Docker image
      run: |
        docker build -t ym-image ./app
        docker run -d --name ym-container -p 5000:5000 ym-image

    - name: Wait for container to start
      run: sleep 15

    - name: Test by requesting data from container
      run: |
        docker ps
        docker exec ym-container curl http://localhost:5000

    - name: Test if container does not have root access
      run: |
        docker exec ym-container id
